# Generated by Django 4.1.7 on 2023-02-17 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, default='Title', max_length=20)),
                ('post_value', models.CharField(blank=True, default='Title', max_length=20)),
                ('post_time', models.DateTimeField(default=datetime.datetime)),
            ],
        ),
    ]
