# Generated by Django 4.1.7 on 2023-02-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_time_alter_post_post_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
